apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-1.0
  labels:
    app: nginx-1.0
    env: prod

spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-1.0

  template:
    metadata:
      labels:
        app: nginx-1.0
    spec:
      containers:
        - name: nginx
          image: nginx:1.19
          ports:
            - containerPort: 80
