apiVersion: v1
kind: Pod
metadata:
  name: multi-label-demo-nginx
  labels:
    environment: production
    app: nginx

spec:
  containers:
  - name: nginx
    image: nginx:1.20
    ports:
    - containerPort: 80