apiVersion: v1
kind: Pod
metadata:
  name: my-pv-pod

spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo Hello Team, This is Persistnent Volume Claim 11 >> /output/success.txt"]
      volumeMounts:
      - mountPath: /output
        name: my-pv
        
  volumes:
    - name: my-pv
      persistentVolumeClaim:
        claimName: my-pvc