apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-1.0
  labels:
    deptype: canary
    env: prod

spec:
  replicas: 3
  selector:
    matchLabels:
      deptype: canary

  template:
    metadata:
      labels:
        deptype: canary
    spec:
      containers:
        - name: nginx
          image: nginx:1.19
          ports:
            - containerPort: 80
