apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod-cmd
spec:
  containers:
    - name: demo
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["echo UI Properties - $(UI_PROPERTIES_FILE_NAME)"]
      env:
        - name: PLAYER_INITIAL_LIVES
          valueFrom:
            configMapKeyRef:
              name: game-demo
              key: player_initial_lives
        - name: UI_PROPERTIES_FILE_NAME
          valueFrom:
            configMapKeyRef:
              name: game-demo
              key: ui_properties_file_name
