apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod-vol2
spec:
  containers:
    - name: demo
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["cat /config/user-interface.properties"]
      
      volumeMounts:
      - name: config
        mountPath: "/config"
        readOnly: true
  volumes:
    - name: config
      configMap:
        name: game-demo
        items:
        - key: "game.properties"
          path: "game.properties"
        - key: "user-interface.properties"
          path: "user-interface.properties"