apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-1.1
  labels:
    app: nginx-1.1
    env: prod

spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-1.1
  template:
    metadata:
      labels:
        app: nginx-1.1
    spec:
      containers:
        - name: nginx
          image: anshuldevops/magicalnginx:latest
          ports:
            - containerPort: 80
